---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - ../base/

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: azuredevops-pat
    envs:
      - .env

patches:
  - path: colconfig.yaml
    target:
      kind: OpenTelemetryCollector
      name: collector
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /metadata/name
        value: otel-azuredevops-collector