---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-operator-system

resources:
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.98.0/opentelemetry-operator.yaml
  - rbac.yaml
