---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openobserve

resources:
  - ../../cluster-infra/namespace/
  - sts.yaml
  - secret.yaml
  - dashboard-bootstrap-job.yaml

configMapGenerator:
  - name: openobserve-dashboards
    files:
      - dashboards/engineering-effectiveness.dashboard.json

generatorOptions:
  disableNameSuffixHash: true

