---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - localized.yaml
  - ./grafana/
  - ./loki/
  - ./prometheus/
  - ./tempo/
  - ./jaeger/
  - ../../collectors/gateway/
